spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
wechat:
  mpAppId: wx1d8cb1c91eacd4d1
  mpAppSecret: 54ed4a0847638f6730d7c4621166edc7
#  mpAppId: wx9a5bff8b90ffbe80
#  mpAppSecret: 081ccf8d549a8d8e6ab5c168a4a742ef
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://cyh.nat300.top/sell/pay/notify
  templateId:
    orderStatus: 6cz7PifGiha4d6Zp89GULcPrdAickUHjW1lbcxI75K4

projectUrl:
  wechatMpAuthorize: http://cyh.nat300.top
  wechatOpenAuthorize: http://cyh.nat300.top
  sell: http://localhost:8080
logging:
  level:
    com.imooc.dataobject.mapper: trace

#mybatis xml
mybatis:
  mapper-locations: classpath:mapper/*.xml